apiVersion: v1
kind: Service
metadata:
  name: nexus3-service
  namespace: default
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8081'
spec:
  selector: 
    app: nexus3
  type: LoadBalancer  
  ports:
    - port: 8081
      targetPort: 8081
     # nodePort: 32001
