apiVersion: v1
kind: Service
metadata:
  name: jenkins-netapp
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    run: jenkins-netapp
  type: LoadBalancer  
  ports:
    - name: httport
      port: 8080
      targetPort: 8080
